In [2]:
import numpy as np
import torch

+ 数据类型及转换

In [ ]:
torch.tensor([1, 2, 3, 4])
torch.tensor([1, 2, 3, 4]).dtype
torch.tensor([1, 2, 3, 4], dtype=torch.double).dtype
torch.tensor(range(10))
np.array([1., 2., 3., 4.]).dtype
np.array([1, 2, 3, 4]).dtype
torch.randn((3, 3)).int()
torch.randn([3, 3]).to(torch.int)
torch.randn(3,3)
torch.randint(0, 5, [3, 3]).to(torch.float)
torch.randint(24,567, (2, 2)).double()  #float32(), float64() isn't work

+ 生成张量

In [49]:
# 0,1均匀分布tensor
torch.rand((3,3))

# 标准正态分布tensor
torch.randn((2, 3, 4))

# 0 tensor
torch.zeros((2, 3, 4))

# 1 tensor
torch.ones([1, 2, 3, 4])

# Identity Matrix
torch.eye(5)

# 均匀分布(整数)的tensor
torch.randint(0, 10, (1, 5, 5))

tensor([[[5, 2, 2, 4, 5],
         [6, 0, 8, 3, 2],
         [3, 0, 1, 1, 4],
         [7, 7, 1, 7, 7],
         [8, 8, 6, 8, 6]]])

+ tensor的储存设备

In [67]:
# 储存在cpu上的tensor
torch.randn((3, 3), device='cpu')

# 储存在0号GPU上的一个tensor 
torch.randn((3, 3), device='cuda:0')

# 储存在1号GPU上面的tensor
try:
    torch.randn((3, 3), device='cuda:1')  # 由于只有1块GPU，此行代码会报错，RuntimeError: CUDA error: invalid device ordinal
except Exception as e:
    print('Trying to store a tensor in "cuda:1", but: \n', e)

# 查看当前tensor所储存的设备
torch.randn((3, 3), device='cuda:0').device

# 将 GPU tensor 转移到 cpu 上
torch.randn((3, 3), device='cuda:0').cpu()

# 将 cpu tensor 转移到 GPU 上
torch.randn((3, 3), device='cpu').cuda(0)

Trying to store a tensor in "cuda:1", but: 
 CUDA error: invalid device ordinal


tensor([[-1.1600,  0.5308,  0.2006],
        [-0.6899,  0.0626,  2.4125],
        [-0.1483,  0.1320, -0.7713]], device='cuda:0')

+ tensor.view 改变形状

In [108]:
t = torch.randn(12)
t1 = torch.randint(0, 5, (2, 6))

# reshape_as 会改变储存地址
t.reshape_as(t1).data_ptr()

# view，不会改变数据地址
t.view((3, 4))
t.data_ptr() == t.view((3, 4)).data_ptr()  # True

# 改变viewed的tensor也会改变之前的tensor
t.view((3,4))[0, 0] = 1
t.view(3, 4).transpose(0,1)  # transpose可以选择两个轴，并转置不会影响tensor储存地址 (permute多轴转置)
t.view(3, 4).transpose(0,1).data_ptr() == t.data_ptr()  # True

# mask
t = torch.randn((2, 3, 5))
t > 0  # Boolean Matrix
(t > 0).to(torch.int)
t[t > 0]  #返回一个向量

tensor([0.9929, 0.5345, 1.4711, 0.1984, 1.8960, 0.2423, 1.5989, 2.2179, 0.9319,
        0.3877, 0.0931, 0.6937, 1.0144, 1.5194])

+ tensor 运算

In [132]:
t1 = torch.rand(3, 4)
print(t1)

# sqrt
t1.sqrt()
torch.sqrt(t1) == t1.sqrt()  # All True, 不会改变t1的值
print(t1)

# sqrt_() In_Place，sqrt直接作用于t1，改变t1的值
t1. sqrt_()
print(t1)

# tensor 求和/求平均
torch.sum(t1)  # 默认维度collapse成1维
torch.sum(t1, 0)   # 按第0维求和
torch.sum(t1, [0, 1])

torch.mean(t1)
torch.mean(t1, [0, 1]) == torch.mean(t1)

torch.sum(t1, 0, keepdim=True)  # keepdim 需要告知operator操作维度，减少多个维度时不能够keepdim

tensor([[0.0719, 0.9478, 0.0220, 0.0564],
        [0.4653, 0.9338, 0.1548, 0.2988],
        [0.1144, 0.2024, 0.4471, 0.8277]])
tensor([[0.0719, 0.9478, 0.0220, 0.0564],
        [0.4653, 0.9338, 0.1548, 0.2988],
        [0.1144, 0.2024, 0.4471, 0.8277]])
tensor([[0.2681, 0.9736, 0.1483, 0.2375],
        [0.6821, 0.9663, 0.3935, 0.5467],
        [0.3382, 0.4499, 0.6687, 0.9098]])


tensor([[1.2884, 2.3898, 1.2104, 1.6940]])

向量的4则运算

In [144]:
t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)

t1.add(t2) == torch.add(t1, t2)  # torch.add

t1.sub(t2) == t1 - t2  # True

t1 * t2 == t1.mul(t2)

t1 / t2 == t1.div(t2)

## 矩阵乘法利用 torch.matmul【适用于高维】， torch.mm【只适用于2维】
## 同理，也存在 tensor1.add_(tensor2) 等tensor内置方法。将会直接改变tensor1的值

tensor([[True, True, True],
        [True, True, True]])

+ 极值与排序函数

In [156]:
t = torch.randn(3, 4)
torch.argmax(t, 0)  # 第0维度的极大值位置
t.argmin(1)

torch.max(t, -1)  # 返回最后一个维度上最大值，最大值index
torch.min(t, -1)

print(t)
print(t.sort(-1))  # 每行从小到大排序


tensor([[-2.0751,  1.8493, -0.7844,  0.6083],
        [-0.8222, -1.5446,  0.3813,  0.9378],
        [ 0.0061,  1.0957,  0.7208,  0.8012]])
torch.return_types.sort(
values=tensor([[-2.0751, -0.7844,  0.6083,  1.8493],
        [-1.5446, -0.8222,  0.3813,  0.9378],
        [ 0.0061,  0.7208,  0.8012,  1.0957]]),
indices=tensor([[0, 2, 3, 1],
        [1, 0, 2, 3],
        [0, 2, 3, 1]]))


+ 矩阵乘法，缩并

In [176]:
a = torch.randn(2, 3, 4)
b = torch.randn(2, 4, 3)

# batch matrix multiplication
torch.bmm(a,b)  # 只能 3-D tensor
a @ b == torch.bmm(a, b)  # @ 可以作为三维以下的矩阵乘法的符号

a1 = torch.randn(2, 3, 4, 5)
b1 = torch.randn(2, 6, 4, 7)
torch.matmul(a, b)  # high_dim tensor matmul, confuse about it operate rule

# **自定义高维乘法规则
torch.einsum('bnk, bkl -> bnl', a, b) == torch.bmm(a, b)
# ⬆ 'bnk, bkl, bnl'代表了tensor维度,字母是什么无所谓，但是要对应。
# ⬆ k就是相加的方向， k在tensor中的维度值要相同

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])

+ tensor拼接，堆叠

In [3]:
t1 = torch.randn(3, 4)
t2 = torch.randn(3, 4)
t3 = torch.randn(3, 4)
t4 = torch.randn(3, 2)

# 沿着最后一个维度堆叠
torch.stack((t1, t2, t3), -1).shape  # return: torch.Size([3, 4, 3])

# 在最后一个维度拼接
torch.cat([t1, t2, t3, t4], -1).shape  # return: torch.Size([3, 14])

# 在最后一个维度进行分割tensor
t = torch.randint(0, 3, [2, 3, 4])
torch.split(t, 2, -1)  # param: Tensor, split_size_seciton, dim; split可以为一个list,分成不等长的section

torch.chunk(t, 3, -1)  # param：Tensor, num, dim; num表示等分成几部分 

(tensor([[[0, 0],
          [1, 1],
          [2, 2]],
 
         [[2, 0],
          [0, 1],
          [2, 2]]]),
 tensor([[[1, 2],
          [2, 2],
          [0, 0]],
 
         [[0, 1],
          [2, 1],
          [2, 0]]]))